from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field, ConfigDict

class RAGSample(BaseModel):
    model_config = ConfigDict(strict=False, populate_by_name=True)

    query: str = Field(..., description="The user query or prompt.")
    retrieved_contexts: List[str] = Field(..., description="List of context strings retrieved from the vector store.")
    context_scores: Optional[List[float]] = Field(None, description="Relevance or distance scores for each context.")
    generated_response: Optional[str] = Field(None, description="The response generated by the LLM.")
    ground_truth: Optional[str] = Field(None, alias="ground_truths", description="The ground truth reference answer.")

class MetricResult(BaseModel):
    metric_name: str
    score: float
    metadata: dict = Field(default_factory=dict)
